// Shared constants used by multiple controllers.
const RENTAL_STATUSES = ['BOOKED', 'ACTIVE', 'COMPLETED', 'CANCELLED'];
const VEHICLE_STATUSES = ['AVAILABLE', 'RENTED', 'MAINTENANCE', 'INACTIVE'];
const PAYMENT_METHODS = ['CASH', 'CARD', 'UPI'];
const PAYMENT_STATUSES = ['PENDING', 'PAID'];
const MAINTENANCE_TYPES = ['SERVICE', 'REPAIR', 'INSPECTION', 'TYRE', 'OTHER'];
const CONDITIONS = ['GOOD', 'FAIR', 'DAMAGED'];
const FUEL_TYPES = ['PETROL', 'DIESEL', 'CNG', 'ELECTRIC', 'HYBRID'];
const TRANSMISSIONS = ['MANUAL', 'AUTOMATIC'];

module.exports = {
  RENTAL_STATUSES, VEHICLE_STATUSES, PAYMENT_METHODS, PAYMENT_STATUSES,
  MAINTENANCE_TYPES, CONDITIONS, FUEL_TYPES, TRANSMISSIONS,
};
